# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- develop

pool:
  vmImage: 'ubuntu-22.04'

steps:

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '16.x'

- task: CmdLine@2
  displayName: Install Dependencies
  inputs:
    script: 'yarn install'

- task: CmdLine@2
  displayName: Install GitPython Dependency
  inputs:
    script: 'python3 -m pip install GitPython'

- task: CmdLine@2
  displayName: Install GitPython Dependency
  inputs:
    script: 'python3 -m pip install ruamel_yaml'

- task: CmdLine@2
  displayName: Install Pillow Dependency
  inputs:
    script: 'python3 -m pip install Pillow'

- task: CmdLine@2
  displayName: Install setuptools Dependency
  inputs:
    script: 'python3 -m pip install setuptools setuptools_rust'

- task: CmdLine@2
  displayName: Install paramiko Dependency
  inputs:
    script: 'python3 -m pip install paramiko'

- task: CmdLine@2
  displayName: Install qrcode Dependency
  inputs:
    script: 'python3 -m pip install qrcode'

- task: CmdLine@2
  displayName: Install androguard Dependency
  inputs:
    script: 'python3 -m pip install androguard'

- task: CmdLine@2
  displayName: Install defusedxml Dependency
  inputs:
    script: 'python3 -m pip install defusedxml'

- task: CmdLine@2
  displayName: Clone frdoiddata
  inputs:
    script: 'git clone https://gitlab.com/fdroid/fdroiddata.git' 
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Clone fdroidserver
  inputs:
    script: 'git clone https://gitlab.com/fdroid/fdroidserver.git'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Copy podverse yml to metadata
  inputs:
    script: 'cp $(Build.Repository.LocalPath)/fdroid/com.podverse.fdroid.yml fdroiddata/metadata'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Log podverse frdoid yml 
  inputs:
    script: 'cat fdroid/com.podverse.fdroid.yml'

- task: CmdLine@2
  displayName: Log fdroiddata metadata podverse yml
  inputs:
    script: 'cat fdroiddata/metadata/com.podverse.fdroid.yml'
    workingDirectory: $(Agent.BuildDirectory)

- task: CmdLine@2
  displayName: Read Metadata
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid readmeta'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Rewrite Metadata
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid rewritemeta com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Lint podverse fdroid config file
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid lint com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: CmdLine@2
  displayName: Build fdroid podverse
  inputs:
    script: '$(Agent.BuildDirectory)/fdroidserver/fdroid build -v -l com.podverse.fdroid'
    workingDirectory: $(Agent.BuildDirectory)/fdroiddata

- task: AndroidSigning@3
  env:
    APK_SIGNER_KEYSTORE_PASSWORD: $(APK_SIGNER_KEYSTORE_PASSWORD)
    APK_SIGNER_KEYSTORE_ALIAS: $(APK_SIGNER_KEYSTORE_ALIAS)
    APK_SIGNER_KEY_PASSWORD: $(APK_SIGNER_KEY_PASSWORD)
  inputs:
    apkFiles: '$(Agent.BuildDirectory)/fdroiddata/build/com.podverse.fdroid/android/app/build/outputs/apk/release/app-release-unsigned.apk'
    apksign: true
    apksignerKeystoreFile: 'podverse-fdroid.keystore'
    apksignerKeystorePassword: $(APK_SIGNER_KEYSTORE_PASSWORD)
    apksignerKeystoreAlias: $(APK_SIGNER_KEYSTORE_ALIAS)
    apksignerKeyPassword: $(APK_SIGNER_KEY_PASSWORD)
    apksignerArguments: --out $(Agent.BuildDirectory)/fdroiddata/build/com.podverse.fdroid/android/app/build/outputs/apk/release/podverse-fdroid.signed.release.apk
    zipalign: true

- task: PublishBuildArtifacts@1
  displayName: Publish build artifact
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)/fdroiddata/build/com.podverse.fdroid/android/app/build/outputs/apk/release'
    ArtifactName: 'app_build'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: Publish metadata artifact
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/fdroid/com.podverse.fdroid.yml'
    ArtifactName: 'metadata'
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'app_build'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: Bash@3
  displayName: Upload APK to BrowserStack
  inputs:
    targetType: 'filePath'
    filePath: $(Build.Repository.LocalPath)/azure-pipelines-post-build.sh
  env:
    APPCENTER_OUTPUT_DIRECTORY: $(System.ArtifactsDirectory)
    BS_USERNAME: $(BS_USERNAME)
    BS_KEY: $(BS_KEY)
    FB_API_KEY: $(FB_API_KEY)
    PLATFORM: 'F-Droid'
